import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "../components/header";
import { Menu, MenuLink } from "../components/menu";
import { DefaultProviders } from "../components/default-providers";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DefaultProviders>
          <Header />
          <div className="main-container">
            <Menu>
              <MenuLink href="/">Dashboard</MenuLink>
              <MenuLink href="/movies">List</MenuLink>
            </Menu>
            <div className="content">{children}</div>
          </div>
        </DefaultProviders>
      </body>
    </html>
  );
}
