import "../styles/globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Header } from "../components/Header";
import { Menu } from "../components/Menu";
import { DefaultProviders } from "../components/DefaultProviders";
import { StyledComponentsRegistry } from "../lib/StyledComponentsRegistry";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <DefaultProviders>
            <Header />
            <div className="main-container">
              <Menu
                items={[
                  { href: "/", label: "Dashboard" },
                  { href: "/movies", label: "List" },
                ]}
              />
              <div className="content">{children}</div>
            </div>
          </DefaultProviders>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
